export const MULTI_INSERT_PRCIING = {
    BASE_PRICE: 195,
    ADDITIONAL_FRAGMENT_PRICE: 50,
    SURCHARGE_PRICE: 50,
    GC_THRESHOLD_PERCENT: 60,
    LENGTH_THRESHOLD_BP: 3000,
};

export const MULTI_MUTAGENESIS_PRICING = {
  BASE_PRICE: 145,           
  ADDITIONAL_MUTATION_PRICE: 50,
  MAX_MUTATIONS: 4,
};

export const OWN_BACKBONE_PRICING = {
    BASE_PRICE: 195,
    ADDITIONAL_FRAGMENT_PRICE: 50,
    SURCHARGE_PRICE: 50,
    GC_THRESHOLD_PERCENT: 60,
    LENGTH_THRESHOLD_BP: 3000,
};